import type { Player, Event, NewsPost, GalleryAlbum } from "./types";

export const players: Player[] = [
  {
    id: "1",
    name: "Alex Rivera",
    position: "Handler",
    number: 7,
    image: "/players/player-1.jpg",
    funFact: "Can throw a hammer 60 meters with pinpoint accuracy",
    yearJoined: 2018,
    isCaptain: true,
  },
  {
    id: "2",
    name: "Jordan Chen",
    position: "Cutter",
    number: 23,
    image: "/players/player-2.jpg",
    funFact: "Former track athlete with a 4.4s 40-yard dash",
    yearJoined: 2019,
  },
  {
    id: "3",
    name: "Sam Martinez",
    position: "Hybrid",
    number: 11,
    image: "/players/player-3.jpg",
    funFact: "Has played Ultimate on 4 continents",
    yearJoined: 2020,
    isCaptain: true,
  },
  {
    id: "4",
    name: "Casey Thompson",
    position: "Handler",
    number: 3,
    image: "/players/player-4.jpg",
    funFact: "Invented the team's signature zone defense",
    yearJoined: 2019,
  },
  {
    id: "5",
    name: "Morgan Lee",
    position: "Cutter",
    number: 15,
    image: "/players/player-5.jpg",
    funFact: "Holds the team record for most layout catches in a season",
    yearJoined: 2021,
  },
  {
    id: "6",
    name: "Riley Johnson",
    position: "Cutter",
    number: 88,
    image: "/players/player-6.jpg",
    funFact: "Never misses a spirit circle speech",
    yearJoined: 2022,
  },
  {
    id: "7",
    name: "Taylor Williams",
    position: "Handler",
    number: 21,
    image: "/players/player-7.jpg",
    funFact: "Introduced the team to post-game pizza tradition",
    yearJoined: 2020,
  },
  {
    id: "8",
    name: "Jamie Park",
    position: "Hybrid",
    number: 42,
    image: "/players/player-8.jpg",
    funFact: "Former college basketball player turned Ultimate convert",
    yearJoined: 2023,
  },
];

export const events: Event[] = [
  {
    id: "1",
    title: "Weekly Practice",
    description:
      "Regular team practice session. All skill levels welcome. Bring water and cleats!",
    date: "2026-01-22",
    time: "18:00",
    endTime: "20:00",
    location: "Golden Gate Park Field 3",
    locationUrl: "https://maps.google.com/?q=Golden+Gate+Park+Field+3",
    type: "practice",
  },
  {
    id: "2",
    title: "League Match vs. Bay Bombers",
    description:
      "Important league match against our cross-town rivals. Arrive 30 minutes early for warm-up.",
    date: "2026-01-25",
    time: "14:00",
    endTime: "16:00",
    location: "Marina Green Field",
    locationUrl: "https://maps.google.com/?q=Marina+Green+San+Francisco",
    type: "match",
    opponent: "Bay Bombers",
  },
  {
    id: "3",
    title: "Weekly Practice",
    description:
      "Regular team practice. Focus on zone offense this week. New players welcome!",
    date: "2026-01-29",
    time: "18:00",
    endTime: "20:00",
    location: "Golden Gate Park Field 3",
    locationUrl: "https://maps.google.com/?q=Golden+Gate+Park+Field+3",
    type: "practice",
  },
  {
    id: "4",
    title: "Team Social - Pizza Night",
    description:
      "Monthly team bonding event. Good food, great company, and maybe some disc golf!",
    date: "2026-02-01",
    time: "19:00",
    location: "Tony's Pizza, North Beach",
    locationUrl: "https://maps.google.com/?q=Tonys+Pizza+North+Beach",
    type: "social",
  },
  {
    id: "5",
    title: "SF Winter Classic Tournament",
    description:
      "Two-day tournament featuring teams from across California. Our biggest event of the season!",
    date: "2026-02-08",
    time: "08:00",
    endTime: "18:00",
    location: "Polo Fields, Golden Gate Park",
    locationUrl: "https://maps.google.com/?q=Polo+Fields+Golden+Gate+Park",
    type: "tournament",
  },
  {
    id: "6",
    title: "Friendly Match vs. Oakland Oaks",
    description: "Casual scrimmage with our friends from across the bay.",
    date: "2026-02-15",
    time: "11:00",
    endTime: "13:00",
    location: "Middle Harbor Park, Oakland",
    locationUrl: "https://maps.google.com/?q=Middle+Harbor+Park+Oakland",
    type: "match",
    opponent: "Oakland Oaks",
  },
];

export const newsPosts: NewsPost[] = [
  {
    id: "1",
    title: "Dynasty Dominates Fall League Championship",
    slug: "dynasty-dominates-fall-championship",
    excerpt:
      "An incredible season finale as Disc Dynasty clinches the Fall League title with an undefeated playoff run.",
    content: `The Disc Dynasty completed their dream season with a convincing 15-11 victory over the Silicon Valley Spinners in the Fall League Championship...`,
    date: "2026-01-15",
    author: "Alex Rivera",
    image: "/news/championship.jpg",
    category: "match-report",
  },
  {
    id: "2",
    title: "Spring Tryouts Announced - New Players Welcome!",
    slug: "spring-tryouts-2026",
    excerpt:
      "Looking to join the Ultimate Frisbee community? Our spring tryout dates are now set.",
    content: `Disc Dynasty is excited to announce our Spring 2026 tryout dates! Whether you're a seasoned player or completely new to the sport...`,
    date: "2026-01-10",
    author: "Sam Martinez",
    image: "/news/tryouts.jpg",
    category: "announcement",
  },
  {
    id: "3",
    title: "Spirit Award: Celebrating Our Community",
    slug: "spirit-award-celebration",
    excerpt:
      "Our team received the League Spirit Award for the third consecutive year.",
    content: `We're proud to announce that Disc Dynasty has been awarded the prestigious League Spirit Award for 2025...`,
    date: "2026-01-05",
    author: "Jordan Chen",
    image: "/news/spirit-award.jpg",
    category: "feature",
  },
];

export const galleryAlbums: GalleryAlbum[] = [
  {
    id: "1",
    title: "Fall Championship 2025",
    description:
      "Photos from our championship victory at the SF Fall League Finals",
    coverImage: "/gallery/championship-cover.jpg",
    googlePhotosUrl: "https://photos.google.com/share/example1",
    date: "2025-12-15",
    photoCount: 48,
  },
  {
    id: "2",
    title: "Team Retreat - Tahoe 2025",
    description: "Annual team bonding trip to Lake Tahoe",
    coverImage: "/gallery/tahoe-cover.jpg",
    googlePhotosUrl: "https://photos.google.com/share/example2",
    date: "2025-11-20",
    photoCount: 72,
  },
  {
    id: "3",
    title: "Summer League Highlights",
    description: "Best moments from the Summer League season",
    coverImage: "/gallery/summer-cover.jpg",
    googlePhotosUrl: "https://photos.google.com/share/example3",
    date: "2025-09-01",
    photoCount: 156,
  },
  {
    id: "4",
    title: "Practice Sessions",
    description: "Behind the scenes at our weekly practices",
    coverImage: "/gallery/practice-cover.jpg",
    googlePhotosUrl: "https://photos.google.com/share/example4",
    date: "2025-08-15",
    photoCount: 34,
  },
];
