import { Event, GalleryAlbum, NewsPost, Player } from "./types";

export const players: Player[] = [
  {
    id: "1",
    name: "Cem",
    number: 7,
    position: "Cutter/Handler",
    bio: "Captain and coordinator of Discobolos. Loves long hucks and spirit of the game.",
    avatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=1000&auto=format&fit=crop",
    isAdmin: true,
  },
  {
    id: "2",
    name: "Deniz",
    number: 23,
    position: "Handler",
    bio: "Precision passer with a mean flick. Always found at the center of the zone.",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=1000&auto=format&fit=crop",
  },
  {
    id: "3",
    name: "Ali",
    number: 10,
    position: "Cutter",
    bio: "High-flying cutter with incredible speed. Known for his game-saving grabs.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1000&auto=format&fit=crop",
  },
  {
    id: "4",
    name: "Selin",
    number: 42,
    position: "Cutter",
    bio: "Relentless defender and expert at reading the wind. Spirit award winner.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1000&auto=format&fit=crop",
  },
  {
    id: "5",
    name: "Burak",
    number: 5,
    position: "Handler",
    bio: "Steady hand in high-pressure situations. Master of the break-mark throw.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1000&auto=format&fit=crop",
  },
];

export const events: Event[] = [
  {
    id: "1",
    title: "Weekly Practice",
    description: "Regular team practice session. All skill levels welcome. Bring water and cleats!",
    date: "2026-01-22",
    time: "18:00",
    endTime: "20:00",
    location: "Golden Gate Park Field 3",
    locationUrl: "https://maps.google.com/?q=Golden+Gate+Park+Field+3",
    type: "practice",
    image: "https://images.unsplash.com/photo-1544698116-e9c9f319b2bc?q=80&w=2000&auto=format&fit=crop",
  },
  {
    id: "2",
    title: "League Match vs. Bay Bombers",
    description: "Important league match against our cross-town rivals. Arrive 30 minutes early for warm-up.",
    date: "2026-01-25",
    time: "14:00",
    endTime: "16:00",
    location: "Marina Green Field",
    locationUrl: "https://maps.google.com/?q=Marina+Green+San+Francisco",
    type: "match",
    opponent: "Bay Bombers",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=2000&auto=format&fit=crop",
  },
  {
    id: "3",
    title: "Deep Defense Drill",
    description: "Special session focused on deep-deep positioning and long disc defense.",
    date: "2026-01-29",
    time: "18:00",
    endTime: "20:00",
    location: "Golden Gate Park Field 3",
    locationUrl: "https://maps.google.com/?q=Golden+Gate+Park+Field+3",
    type: "practice",
    image: "https://images.unsplash.com/photo-1542332213-31f87348057f?q=80&w=2000&auto=format&fit=crop",
  },
  {
    id: "4",
    title: "Team Social - Pizza Night",
    description: "Monthly team bonding event. Good food, great company, and maybe some disc golf!",
    date: "2026-02-01",
    time: "19:00",
    location: "Tony's Pizza, North Beach",
    locationUrl: "https://maps.google.com/?q=Tonys+Pizza+North+Beach",
    type: "social",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=2000&auto=format&fit=crop",
  },
  {
    id: "5",
    title: "SF Winter Classic Tournament",
    description: "Two-day tournament featuring teams from across California. Our biggest event of the season!",
    date: "2026-02-08",
    time: "08:00",
    endTime: "18:00",
    location: "Polo Fields, Golden Gate Park",
    locationUrl: "https://maps.google.com/?q=Polo+Fields+Golden+Gate+Park",
    type: "tournament",
    image: "https://images.unsplash.com/photo-1504450758481-7338eba7524a?q=80&w=2000&auto=format&fit=crop",
  },
  {
    id: "6",
    title: "Friendly Match vs. Oakland Oaks",
    description: "Casual scrimmage with our friends from across the bay.",
    date: "2026-02-15",
    time: "11:00",
    endTime: "13:00",
    location: "Bushrod Park, Oakland",
    locationUrl: "https://maps.google.com/?q=Bushrod+Park+Oakland",
    type: "match",
    opponent: "Oakland Oaks",
    image: "https://images.unsplash.com/photo-1518604666860-9ed391f76460?q=80&w=2000&auto=format&fit=crop",
  },
];

export const newsPosts: NewsPost[] = [
  {
    id: "1",
    title: "Discobolos Wins Spirit Award at Beach Classic",
    excerpt: "The team showed incredible spirit and sportsmanship throughout the two-day tournament, earning the highest votes from opponents.",
    content: "Full report coming soon...",
    date: "2024-05-15",
    category: "match-report",
    image: "https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2000&auto=format&fit=crop",
  },
  {
    id: "2",
    title: "New Training Schedule for Summer Season",
    excerpt: "We're moving our weekday practices to Camel Beach to make the most of the evening sun. Check the updated calendar for details.",
    content: "Full report coming soon...",
    date: "2024-06-01",
    category: "announcement",
    image: "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?q=80&w=2000&auto=format&fit=crop",
  },
  {
    id: "3",
    title: "Spotlight: Exploring the History of Ultimate in Bodrum",
    excerpt: "How a small group of friends turned a hobby into a thriving community that thrives on the Aegean coast.",
    content: "Full report coming soon...",
    date: "2024-06-10",
    category: "feature",
    image: "https://images.unsplash.com/photo-1544698116-e9c9f319b2bc?q=80&w=2000&auto=format&fit=crop",
  },
];

export const galleryAlbums: GalleryAlbum[] = [
  {
    id: "1",
    title: "Summer Beach Classic 2024",
    description: "Highlights from our annual tournament at Camel Beach. Great sun, great sand, even better frisbee!",
    coverImage: "https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2000&auto=format&fit=crop",
    googlePhotosUrl: "https://photos.app.goo.gl/example1",
    date: "2024-05-12",
    photoCount: 45,
    previewImages: [
      "https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=800&auto=format",
      "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?q=80&w=800&auto=format",
    ],
  },
  {
    id: "2",
    title: "Winter Indoor League",
    description: "Chasing the disc even when the weather doesn't cooperate. Fast-paced action from our indoor sessions.",
    coverImage: "https://images.unsplash.com/photo-1518604666860-9ed391f76460?q=80&w=2000&auto=format&fit=crop",
    googlePhotosUrl: "https://photos.app.goo.gl/example2",
    date: "2024-02-15",
    photoCount: 28,
  },
  {
    id: "3",
    title: "Team Hike to Ancient Ruins",
    description: "Exploring the surroundings of Halicarnassus. Sometimes we trade our cleats for hiking boots.",
    coverImage: "https://images.unsplash.com/photo-1627916843394-fa202a0a256a?q=80&w=2000&auto=format&fit=crop",
    googlePhotosUrl: "https://photos.app.goo.gl/example3",
    date: "2024-03-22",
    photoCount: 15,
  },
];
